info:
  profile: dev
  name: xishuai
  password: {cipher}AQCYgQ0S69sf/HaMBRWx1UVHdIyCsxq/iyCmzD/mLezu6xmHe9cpueXoGv+n8ki6JEEtmM1EsyeubRyWI0+Zf4XHJIE85ZXGmk3bOXYEflWSq4UW8XR5ELwPlap5jjfLVgxcjXCRETDYl6ec4m41PBDRdmNRuHpYZ9N/6jSKH5mnrUBHcTfLDJ3dT3JGc/c4lYkqIuBwVf5+4Gujp1Jk6V9r8WO812hSHrE/NTLCeQWh+ruz4/l8lPHfEIMrTSUmYAJLhRo37ucOoVlG2ukzPRgEYbs1o5tOOArcx5WJBJmMXLjgkMMlkpMTtwxoYtWP6pydKhsiiCbLfx8ho50slLzDxqBnIM2NcgqhhAsc6uboDk4PDYjGQ8edW/2uJYSbqoQ=%
